read:
  - CLAUDE.md
  - spec.md
  - prompt_plan.md
cache-prompts: true
auto-commits: false
git-commit-verify: true
lint: false
auto-lint: false
test-cmd: "python -m pytest -v" 
auto-test: false
verbose: false
yes-always: true
editor: nvim
